apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world-container
        image: idan535/hello-world-app:latest
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: my-docker-secret
