name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y conntrack golang-go git

    - name: Clone cri-dockerd
      run: |
        git clone https://github.com/Mirantis/cri-dockerd.git
        cd cri-dockerd
        git checkout v0.2.4  # או גרסה מתאימה אחרת
        make
        sudo make install

    - name: Download and install Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube

    - name: Start Minikube
      run: |
        minikube start --driver=none

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Configure kubectl
      run: |
        minikube kubectl -- config view --raw > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig

    - name: Debug kubectl
      run: |
        KUBECONFIG=$(pwd)/kubeconfig kubectl cluster-info
        KUBECONFIG=$(pwd)/kubeconfig kubectl get nodes

    - name: Deploy to Kubernetes
      run: |
        KUBECONFIG=$(pwd)/kubeconfig kubectl set image deployment/hello-world-app hello-world-container=idan535/hello-world-app:latest
