name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t idan535/my-image:latest .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push idan535/my-image:latest

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y conntrack golang-go git

    - name: Install cri-dockerd
      run: |
        git clone https://github.com/Mirantis/cri-dockerd.git
        cd cri-dockerd
        git checkout v0.2.4
        make build  # Build the cri-dockerd binary
        sudo cp cri-dockerd /usr/local/bin/cri-dockerd  # Copy the binary to the right location

    - name: Set up Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        minikube start --driver=none

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/my-app my-container=idan535/my-image:latest
