name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # או הבראנצ'ים המתאימים

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t idan535/hello-world-app:latest .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push idan535/hello-world-app:latest

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y conntrack
        curl -LO https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.26.0/crictl-v1.26.0-linux-amd64.tar.gz
        tar -xzvf crictl-v1.26.0-linux-amd64.tar.gz -C /tmp
        sudo cp /tmp/crictl /usr/local/bin/
        sudo chmod +x /usr/local/bin/crictl

    - name: Install cri-dockerd
      run: |
        git clone https://github.com/Mirantis/cri-dockerd.git
        cd cri-dockerd
        git checkout v0.2.4  # בחר גרסה מתאימה
        sudo make build
        sudo cp cri-dockerd /usr/local/bin/

    - name: Install Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        minikube start --driver=none

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Configure kubectl
      run: |
        minikube kubectl -- config view --raw > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig

    - name: Debug kubectl
      run: |
        KUBECONFIG=$(pwd)/kubeconfig kubectl cluster-info
        KUBECONFIG=$(pwd)/kubeconfig kubectl get nodes

    - name: Deploy to Kubernetes
      run: |
        KUBECONFIG=$(pwd)/kubeconfig kubectl set image deployment/hello-world-app hello-world-container=idan535/hello-world-app:latest
